apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>{{ .Values.pageTitile }}-{{ .Values.image.tag }} </title>
    </head>
    <body>

    <h1>{{ .Values.pageTitile }}</h1>

    </body>
    </html>
