kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: {{ .Values.image.repository }} 
        image: {{ .Values.image.tag }} 
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: kargo-demo-content